# Dockerfile.mssql-tools
FROM mcr.microsoft.com/mssql/server:2022-latest

USER root

RUN apt-get update \
 && ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev \
 && ln -s /opt/mssql-tools/bin/sqlcmd /usr/bin/sqlcmd \
 && ln -s /opt/mssql-tools/bin/bcp /usr/bin/bcp \
 && rm -rf /var/lib/apt/lists/*

USER mssql
